# Generated by Django 4.1.1 on 2022-10-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement_type',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Order', 'Order'), ('Invoice', 'Invoice')], default='Quote', max_length=50),
        ),
        migrations.DeleteModel(
            name='StatementType',
        ),
    ]
