# Generated by Django 4.1.1 on 2022-10-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invoice_date_alter_quotation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
