# Generated by Django 4.1.1 on 2022-10-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_statementline_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.FloatField(default=5),
        ),
    ]
