# Generated by Django 4.0.7 on 2022-11-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quotation_comment_alter_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Refuse', 'Refuse')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='sale_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_lines', to='core.saleorder'),
        ),
    ]
